apiVersion: v1
kind: DeploymentConfig
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
        image: bibinwilson/redis:4.1
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2500Mi
          requests:
            cpu: 500m
            memory: 2500Mi
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-master-data
