apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
  namespace: redis-cluster
spec:
  clusterIP: 
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    redis-sentinel: 'true'
  sessionAffinity: None
  type: ClusterIP
